services:
  - type: web
    name: edunexus-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/Edunexus-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,http://localhost:3000,https://animesh292.github.io,https://*.vercel.app,https://*.netlify.app
